name: churn_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - numpy
  - xgboost
  - lightgbm
  - jupyter
  - streamlit
  - plotly
  - bambi
  - arviz
  - mlflow>=2.14
  - protobuf>=3.20,<5
  - click>=8.0.0,<8.2.0
  - werkzeug<3.0.0
  - flask<3.0.0