name: churn_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - numpy
  - xgboost
  - lightgbm
  - jupyter
  - streamlit
  - plotly
  - bambi
  - arviz
  - mlflow[version='>=2.14']
  - protobuf[version='>=3.20,<5']
  - click[version='>=8.0.0,<8.2.0']
  - flask[version='<3.0.0']
  - werkzeug[version='<3.0.0']
  - shap
